#	@(#)Makefile	5.3 (Berkeley) 5/11/90
#
#	$Header: /usr/tmp/cvs2git/cvsroot-netbsd/src/sbin/ifconfig/Makefile,v 1.3 1993/03/23 00:28:28 cgd Exp $

PROG=	ifconfig
MAN8=	ifconfig.0

.include <bsd.prog.mk>
