#	@(#)Makefile	5.3 (Berkeley) 5/11/90
#
#	$Header: /usr/tmp/cvs2git/cvsroot-netbsd/src/sbin/badsect/Makefile,v 1.3 1993/03/23 00:26:22 cgd Exp $

PROG=	badsect
MAN8=	badsect.0

.include <bsd.prog.mk>
